[versions]
dokka = "1.9.20"
kotlin = "2.0.20"
spotless = "6.25.0"
java = "17"
kotlinxSerialization = "1.6.2"
nimbusJoseWwt = "9.37.3"
ktlintVersion = "0.50.0"
sonarqube = "5.1.0.4882"
dependencycheck = "10.0.4"
maven-publish = "0.29.0"
kotlinx-knit = "0.5.0"
tink = "1.15.0"
kotlinxCoroutines = "1.8.1"
ktor = "2.3.12"

[libraries]
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerialization" }
nimbus-jose-jwt = { module = "com.nimbusds:nimbus-jose-jwt", version.ref = "nimbusJoseWwt" }
tink = { module = "com.google.crypto.tink:tink", version.ref = "tink" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutines" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-serialization = { module = "io.ktor:ktor-client-serialization", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-client-mock = { module = "io.ktor:ktor-client-mock", version.ref = "ktor" }

[plugins]
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-plugin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
dependencycheck = { id = "org.owasp.dependencycheck", version.ref = "dependencycheck" }
sonarqube = { id = "org.sonarqube", version.ref = "sonarqube" }
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "maven-publish" }
kotlinx-knit = { id = "org.jetbrains.kotlinx.knit", version.ref = "kotlinx-knit" }
