[versions]
dokka = "1.9.20"
kotlin = "1.9.22"
foojay = "0.8.0"
spotless = "6.25.0"
java = "17"
kotlinxSerialization = "1.6.2"
nimbusJoseWwt = "9.37.3"
ktlintVersion = "0.50.0"
sonarqube = "5.0.0.4638"
dependencycheck = "9.1.0"
maven-publish = "0.28.0"
kotlinx-knit = "0.5.0"
tink = "1.13.0"
jsonpathkt = "2.0.1"

[libraries]
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerialization" }
nimbus-jose-jwt = { module = "com.nimbusds:nimbus-jose-jwt", version.ref = "nimbusJoseWwt" }
tink = { module = "com.google.crypto.tink:tink", version.ref = "tink" }
jsonpathkt = { module = "com.nfeld.jsonpathkt:jsonpathkt", version.ref = "jsonpathkt" }

[plugins]
foojay-resolver-convention = { id = "org.gradle.toolchains.foojay-resolver-convention", version.ref = "foojay" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-plugin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
dependencycheck = { id = "org.owasp.dependencycheck", version.ref = "dependencycheck" }
sonarqube = { id = "org.sonarqube", version.ref = "sonarqube" }
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "maven-publish" }
kotlinx-knit = { id = "org.jetbrains.kotlinx.knit", version.ref = "kotlinx-knit" }
