[versions]
dokka = "1.9.10"
kotlin = "1.9.21"
foojay = "0.7.0"
spotless = "6.23.2"
java = "17"
kotlinxSerialization = "1.6.1"
nimbusJoseWwt = "9.37.1"
ktlintVersion = "0.50.0"
sonarqube = "4.4.1.3373"
dependencycheck = "9.0.2"
maven-publish = "0.25.3"

[libraries]
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerialization" }
nimbus-jose-jwt = { module = "com.nimbusds:nimbus-jose-jwt", version.ref = "nimbusJoseWwt" }

[plugins]
foojay-resolver-convention = { id = "org.gradle.toolchains.foojay-resolver-convention", version.ref = "foojay" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-plugin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
dependencycheck = { id = "org.owasp.dependencycheck", version.ref = "dependencycheck" }
sonarqube = { id = "org.sonarqube", version.ref = "sonarqube" }
maven-publish = { id = "com.vanniktech.maven.publish", version.ref="maven-publish" }
